sudo: false
language: bash
os:
- linux
env:
  global:
  - BUILD_FOLDER=$TRAVIS_BUILD_DIR/build.tmp
  - SKETCH_LOCATION="$TRAVIS_BUILD_DIR"
  - LIBRARIES_LOCATION="-l $HOME/Arduino/libraries"
  - BOARD_TYPE="-b generic"
  - FLASH_SIZE="-s 4M3M"
  - CPU_SPEED="-f 160"
  - OUTPUT_FILE="-o $TRAVIS_BUILD_DIR/firmware.bin"
  - DEBUG_PORT="--debug_port Serial"
before_install:
- ssh-keyscan -t ssh-dss,rsa,ecdsa -p 4022 -H $DEPLOY_DEST 2>&1 | tee -a $HOME/.ssh/known_hosts
install:
- wget -O arduino.tar.xz https://www.arduino.cc/download.php?f=/arduino-nightly-linux64.tar.xz
- tar xf arduino.tar.xz
- mv arduino-nightly $HOME/arduino_ide
- cd $HOME/arduino_ide/hardware
- mkdir esp8266com
- cd esp8266com
- git clone https://github.com/sticilface/arduino-esp8266 esp8266
- cd esp8266/tools
- python get.py
- export PATH="$HOME/arduino_ide:$HOME/arduino_ide/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin:$PATH"
- which arduino
- which xtensa-lx106-elf-size
- cd $TRAVIS_BUILD_DIR
- source $HOME/arduino_ide/hardware/esp8266com/esp8266/tests/common.sh
- git clone https://github.com/sticilface/mypythondeployscript $HOME/scripts
- mkdir -p $HOME/Arduino/libraries
- git clone https://github.com/bblanchon/ArduinoJson          $HOME/Arduino/libraries/ArduinoJson
- git clone https://github.com/me-no-dev/ESPAsyncTCP          $HOME/Arduino/libraries/ESPAsyncTCP
- git clone https://github.com/me-no-dev/ESPAsyncWebServer    $HOME/Arduino/libraries/ESPAsyncWebServer
- git clone https://github.com/Makuna/NeoPixelBus             $HOME/Arduino/libraries/NeoPixelBus
- git clone https://github.com/knolleary/pubsubclient         $HOME/Arduino/libraries/pubsubclient
- git clone https://github.com/adafruit/Adafruit-GFX-Library  $HOME/Arduino/libraries/Adafruit-GFX-Library
- git clone -b upgrade-gui https://github.com/sticilface/ESPmanager    $HOME/Arduino/libraries/ESPmanager
- git clone -b async https://github.com/sticilface/Melvanimate         $HOME/Arduino/libraries/Melvanimate
- cd $TRAVIS_BUILD_DIR
script:
- echo -e "travis_fold:end:sketch_test_env_prepare"
- echo -e "travis_fold:start:sketch_test"
- build_sketches $HOME/arduino_ide $SKETCH_LOCATION $BUILD_FOLDER "$LIBRARIES_LOCATION
  $OUTPUT_FILE $BOARD_TYPE $FLASH_SIZE $CPU_SPEED $DEBUG_PORT $DEBUG_LEVEL"
- echo -e "travis_fold:end:sketch_test"
after_success:
- echo -e "travis_fold:start:size_report"
- cat size.log
- echo -e "travis_fold:end:size_report"
- ls -la $TRAVIS_BUILD_DIR/*.bin
- mkdir /tmp/package
- cp $TRAVIS_BUILD_DIR/firmware.bin "/tmp/package/firmware.bin"
- cp -r "$SKETCH_LOCATION/data" "/tmp/package/"
- cp -r "$HOME/Arduino/libraries/ESPmanager/data" "/tmp/package/"
- ls /tmp/package/
deploy:
- provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script: /bin/sh $TRAVIS_BUILD_DIR/travis/deploy.sh latest
